#' @import(tidyr)
NULL

#' Function to calculate neighbors within a specified radius
#'
#' @param plot A ROI multi-feature plot generated by plot_b2c
#' @param radius The maximum distance (microns) within which neighbors are to be detected
#' @param thresholds The thresholds used to generate the plot with plot_b2c
#' @return A data frame with distances data
#' @export
get_dist <- function(plot, radius = 100, thresholds = c(0,0)) {

  # convert radius to micron (based on 2um bins)
  radius <- radius/2

  # filter
  dfcols <- plot$data[,3:(length(thresholds)+2)]
  df <- plot$data[rowSums(sweep(as.matrix(dfcols), 2, thresholds, ">")) > 0, ]

  # reshape
  df <- pivot_longer(df, cols = 3:(length(thresholds) + 2),
                     names_to = "variable", values_to = "value")

  df <- split(df, df$variable)
  for(i in 1:length(df)) {
    df[[i]] <- df[[i]][df[[i]]$value > thresholds[i],]
  }
  df <- do.call("rbind", df)

  # Calculate neighbors within radius
  results <- list()
  for (i in seq_len(nrow(df))) {
    current_cell <- df[i, ]
    distances <- sqrt((df$SPATIAL_1 - current_cell$SPATIAL_1)^2 +
                        (df$SPATIAL_2 - current_cell$SPATIAL_2)^2)
    neighbors <- df[distances <= radius & distances > 0, ]
    if (nrow(neighbors) > 0) {
      neighbors <- neighbors[,3:5] %>%
        mutate(distance = distances[distances <= radius & distances > 0] * 2) # *2 to convert back to 2um bins
      results[[i]] <- data.frame(
        origin_name = current_cell[,3],
        origin_marker = current_cell$variable,
        origin_value = current_cell$value,
        neighbor_name = neighbors[,1],
        neighbor_marker = neighbors$variable,
        neighbor_value = neighbors$value,
        distance = neighbors$distance
      )
    } else {
      results[[i]] <- data.frame(
        origin_name = current_cell[,3],
        origin_marker = current_cell$variable,
        origin_value = current_cell$value,
        neighbor_name = NA,
        neighbor_marker = NA,
        neighbor_value = NA,
        distance = NA
      )
    }
    # Ensure consistent colnames
    colnames(results[[i]]) <- c("origin_name", "origin_marker", "origin_value", "neighbor_name", "neighbor_marker", "neighbor_value", "distance")
  }
  final_output <- do.call(rbind, results)
  final_output <- final_output[complete.cases(final_output),]
  return(final_output)
}
