#' @importFrom tidyr pivot_longer
NULL

#' Function to calculate neighbors within a specified radius
#'
#' @param plot A ROI feature plot generated by plot_b2c (with plot = FALSE)
#' @param radius The maximum distance (microns) within which neighbors are to be detected
#' @return A list with two elements: \code{distances} (a data frame with pairwise distance data)
#'   and \code{locations} (a data frame with cell_id, x, y coordinates)
#' @export
get_dist <- function(plot, radius = 100) {

  # filter
  dfcols <- plot$cells[,3:(length(plot$threshold)+2)]
  df <- plot$cells[rowSums(sweep(as.matrix(dfcols), 2, plot$threshold, ">")) > 0, ]

  # reshape
  df <- plot$cells
  df <- tidyr::pivot_longer(df, cols = 3:(length(df) - 1),
                             names_to = "variable", values_to = "value")

  df <- split(df, df$variable)
  for(i in 1:length(df)) {
    if(is.factor(df[[i]]$value)) next  # skip if feature is a factor
    df[[i]] <- df[[i]][df[[i]]$value > plot$threshold[i],]
  }
  df <- do.call("rbind", df)

  # Calculate neighbors within radius
  results <- list()
  for (i in seq_len(nrow(df))) {
    current_cell <- df[i, ]
    distances <- sqrt((df$SPATIAL_1 - current_cell$SPATIAL_1)^2 +
                        (df$SPATIAL_2 - current_cell$SPATIAL_2)^2)
    neighbors <- df[distances <= radius & distances > 0, ]
    if (nrow(neighbors) > 0) {
      neighbors <- neighbors[,3:5] %>%
        dplyr::mutate(distance = distances[distances <= radius & distances > 0])
      results[[i]] <- data.frame(
        origin_name = current_cell[,3],
        origin_marker = current_cell$variable,
        origin_value = current_cell$value,
        neighbor_name = neighbors[,1],
        neighbor_marker = neighbors$variable,
        neighbor_value = neighbors$value,
        distance = neighbors$distance
      )
    } else {
      results[[i]] <- data.frame(
        origin_name = current_cell[,3],
        origin_marker = current_cell$variable,
        origin_value = current_cell$value,
        neighbor_name = NA,
        neighbor_marker = NA,
        neighbor_value = NA,
        distance = NA
      )
    }
    # Ensure consistent colnames
    colnames(results[[i]]) <- c("origin_name", "origin_marker", "origin_value", "neighbor_name", "neighbor_marker", "neighbor_value", "distance")
  }
  final_output <- do.call(rbind, results)
  final_output <- final_output[complete.cases(final_output),]
  return(list(
    distances = final_output,
    locations = plot$cells[,c(length(plot$cells), 1, 2)] %>%
      setNames(c("cell_id", "x", "y"))
  ))
}
